name: Test with Docker Compose

on:
  push:
    branches:
      - main

env:
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  SPRING_DATASOURCE_ROOT_PASSWORD: ${{ secrets.SPRING_DATASOURCE_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secretsMYSQL_DATABASE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and run Docker Compose
        run: docker-compose up -d --build

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Shutdown Docker Compose
        run: docker-compose down