name: Test with Docker Compose

on:
  push:
    branches:
      - main

env:
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  SPRING_DATASOURCE_ROOT_PASSWORD: ${{ secrets.SPRING_DATASOURCE_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y
        shell: bash

      - name: Build and run Docker Compose
        run: docker-compose up -d --build
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Test Project
        run: ./gradlew test
        shell: bash

      - name: Shutdown Docker Compose
        run: docker-compose down